server.port=8081
management.endpoints.web.exposure.include=health,info,metrics

management.endpoint.health.show-details=always

management.endpoint.health.probes.enabled=true

info.app.name=My Application
info.app.version=1.0.0
info.app.description=Spring Boot Backend
